[package]
cairo-version = "2.10.1"
name = "whaleopoly_contracts"
version = "1.5.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate"                      # scarb run migrate
join_game = "sozo execute actions join_game --wait"         # scarb run join_game
roll_dice = "sozo execute actions roll_dice --wait"         # scarb run roll_dice
buy_property = "sozo execute actions buy_property --wait"   # scarb run buy_property

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.5.0" }

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[dev-dependencies]
cairo_test = "2.10.1"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.5.0" }
